### PR TITLE
Reorganize Red Queen into a python package

### PR DESCRIPTION
**Pull request by mtreinish**
This commit reorganize the red queen project into a python project.
Previously red queen wasn't organized as a single package which caused
potential issues when trying to run or interact between the packages.
This commit changes the repository structure to move all the code into
the red_queen package so it is all self contained. This also enables us
to create a python package with setuptools which increases future
flexibility by enabling us to publish console scripts which will be
include when the package is built and installed.

### CODE REVIEW

**Review by Lementknight — APPROVED** [review]
I don't see any problems with the new structure, and I believe that your commits are ready to be pushed.

**Comment by Yelissal** [comment]
Very well explained! The comments were very helpful. I also believe the commits are ready to be pushed.

**Review by Yelissal — APPROVED** [review]
Very well explained! The comments were very helpful. I also believe the commits are ready to be pushed.

**Review by danielleodigie — APPROVED** [review]
This makes sense, it's low-key cool to see how making a python package works, makes it less scary :0, but overall LGTM!

**Comment by keilydluna** [comment]
I agree with Danielle. This is efficient and understandable. LGTM!

**Review by keilydluna — APPROVED** [review]

**Review by raynelfss — APPROVED** [review]
The new changes work as intended and the new structure makes it easier to install all dependencies by pip-installing the repository as a python module. Looks good to me!

**Comment by mtreinish** [comment]
Thanks for the review everyone!

**Pull request merged**
